#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu, 23 Mar 2023 06:10:24 +0000

@author: Shallyn
"""
import numpy as np
import matplotlib.pyplot as plt
import sys, os
from pathlib import Path
import ctypes

class pyREAL8Vector(ctypes.Structure):
    _fields_ = (('length', ctypes.c_uint),
                ('data', ctypes.POINTER(ctypes.c_double)))

class c_complex(ctypes.Structure):
    _fields_ = (('real', ctypes.c_double),
                ('imag', ctypes.c_double))
    @property
    def value(self):
        return self.real+1j*self.imag # fields declared above

c_double_complex_p = ctypes.POINTER(c_complex)
c_double_p = ctypes.POINTER(ctypes.c_double)
b_double_complex = lambda c: ctypes.byref(c_complex(c.real, c.imag))

class pyHyperParams(ctypes.Structure):
    _fields_ = (('sl_p', ctypes.c_double),
                ('x0', ctypes.c_double),
                ('KK', ctypes.c_double),
                ('dSO', ctypes.c_double),
                ('dSS', ctypes.c_double),
                ('dtPeak', ctypes.c_double),
                ('flagTuning', ctypes.c_int),
                ('flagZframe', ctypes.c_int),
                ('d_ini', ctypes.c_double),
                ('pr_ini', ctypes.c_double),
                ('pphi_ini', ctypes.c_double),
                ('ptheta_ini', ctypes.c_double),
                ('tStepBack', ctypes.c_double))

class pyFacWaveformCoeffs(ctypes.Structure):
    _fields_ = (('delta22vh3',ctypes.c_double),
                ('delta22vh6',ctypes.c_double),
                ('delta22vh6S',ctypes.c_double),
                ('delta22v8',ctypes.c_double),
                ('delta22v8S',ctypes.c_double),
                ('delta22vh9',ctypes.c_double),
                ('delta22v5',ctypes.c_double),
                ('delta22v6',ctypes.c_double),
                ('delta22v6S',ctypes.c_double),
                ('rho22v2',ctypes.c_double),
                ('rho22v3',ctypes.c_double),
                ('rho22v3S',ctypes.c_double),
                ('rho22v4',ctypes.c_double),
                ('rho22v4S',ctypes.c_double),
                ('rho22v5',ctypes.c_double),
                ('rho22v5S',ctypes.c_double),
                ('rho22v6',ctypes.c_double),
                ('rho22v6S',ctypes.c_double),
                ('rho22v6l',ctypes.c_double),
                ('rho22v7',ctypes.c_double),
                ('rho22v7S',ctypes.c_double),
                ('rho22v8',ctypes.c_double),
                ('rho22v8S',ctypes.c_double),
                ('rho22v8l',ctypes.c_double),
                ('rho22v10',ctypes.c_double),
                ('rho22v10l',ctypes.c_double),
                ('delta21vh3',ctypes.c_double),
                ('delta21vh6',ctypes.c_double),
                ('delta21vh6S',ctypes.c_double),
                ('delta21vh7',ctypes.c_double),
                ('delta21vh7S',ctypes.c_double),
                ('delta21vh9',ctypes.c_double),
                ('delta21v5',ctypes.c_double),
                ('delta21v7',ctypes.c_double),
                ('rho21v1',ctypes.c_double),
                ('rho21v2',ctypes.c_double),
                ('rho21v2S',ctypes.c_double),
                ('rho21v3',ctypes.c_double),
                ('rho21v3S',ctypes.c_double),
                ('rho21v4',ctypes.c_double),
                ('rho21v4S',ctypes.c_double),
                ('rho21v5',ctypes.c_double),
                ('rho21v5S',ctypes.c_double),
                ('rho21v6',ctypes.c_double),
                ('rho21v6S',ctypes.c_double),
                ('rho21v6l',ctypes.c_double),
                ('rho21v7',ctypes.c_double),
                ('rho21v7S',ctypes.c_double),
                ('rho21v7l',ctypes.c_double),
                ('rho21v7lS',ctypes.c_double),
                ('rho21v8',ctypes.c_double),
                ('rho21v8l',ctypes.c_double),
                ('rho21v10',ctypes.c_double),
                ('rho21v10l',ctypes.c_double),
                ('f21v1',ctypes.c_double),
                ('f21v1S',ctypes.c_double),
                ('f21v3',ctypes.c_double),
                ('f21v3S',ctypes.c_double),
                ('f21v4',ctypes.c_double),
                ('f21v5',ctypes.c_double),
                ('f21v6',ctypes.c_double),
                ('f21v7c',ctypes.c_double),
                ('f21v7cEff00',ctypes.c_double),
                ('f21v7cEff10',ctypes.c_double),
                ('f21v7cEff11',ctypes.c_double),
                ('f21v7cEff01',ctypes.c_double),
                ('f21v7cEff02',ctypes.c_double),
                ('delta33vh3',ctypes.c_double),
                ('delta33vh6',ctypes.c_double),
                ('delta33vh6S',ctypes.c_double),
                ('delta33vh9',ctypes.c_double),
                ('delta33v5',ctypes.c_double),
                ('delta33v7',ctypes.c_double),
                ('rho33v2',ctypes.c_double),
                ('rho33v3',ctypes.c_double),
                ('rho33v4',ctypes.c_double),
                ('rho33v4S',ctypes.c_double),
                ('rho33v5',ctypes.c_double),
                ('rho33v5S',ctypes.c_double),
                ('rho33v6',ctypes.c_double),
                ('rho33v6S',ctypes.c_double),
                ('rho33v6l',ctypes.c_double),
                ('rho33v7',ctypes.c_double),
                ('rho33v7S',ctypes.c_double),
                ('rho33v8',ctypes.c_double),
                ('rho33v8l',ctypes.c_double),
                ('rho33v10',ctypes.c_double),
                ('rho33v10l',ctypes.c_double),
                ('f33v3',ctypes.c_double),
                ('f33v4',ctypes.c_double),
                ('f33v5',ctypes.c_double),
                ('f33v6',ctypes.c_double),
                ('f33v3S',ctypes.c_double),
                ('f33vh6',ctypes.c_double),
                ('delta32vh3',ctypes.c_double),
                ('delta32vh4',ctypes.c_double),
                ('delta32vh4S',ctypes.c_double),
                ('delta32vh6',ctypes.c_double),
                ('delta32vh6S',ctypes.c_double),
                ('delta32vh9',ctypes.c_double),
                ('rho32v',ctypes.c_double),
                ('rho32vS',ctypes.c_double),
                ('rho32v2',ctypes.c_double),
                ('rho32v2S',ctypes.c_double),
                ('rho32v3',ctypes.c_double),
                ('rho32v3S',ctypes.c_double),
                ('rho32v4',ctypes.c_double),
                ('rho32v4S',ctypes.c_double),
                ('rho32v5',ctypes.c_double),
                ('rho32v5S',ctypes.c_double),
                ('rho32v6',ctypes.c_double),
                ('rho32v6S',ctypes.c_double),
                ('rho32v6l',ctypes.c_double),
                ('rho32v8',ctypes.c_double),
                ('rho32v8l',ctypes.c_double),
                ('delta31vh3',ctypes.c_double),
                ('delta31vh6',ctypes.c_double),
                ('delta31vh6S',ctypes.c_double),
                ('delta31vh7',ctypes.c_double),
                ('delta31vh7S',ctypes.c_double),
                ('delta31vh9',ctypes.c_double),
                ('delta31v5',ctypes.c_double),
                ('rho31v2',ctypes.c_double),
                ('rho31v3',ctypes.c_double),
                ('rho31v4',ctypes.c_double),
                ('rho31v4S',ctypes.c_double),
                ('rho31v5',ctypes.c_double),
                ('rho31v5S',ctypes.c_double),
                ('rho31v6',ctypes.c_double),
                ('rho31v6S',ctypes.c_double),
                ('rho31v6l',ctypes.c_double),
                ('rho31v7',ctypes.c_double),
                ('rho31v7S',ctypes.c_double),
                ('rho31v8',ctypes.c_double),
                ('rho31v8l',ctypes.c_double),
                ('f31v3',ctypes.c_double),
                ('f31v3S',ctypes.c_double),
                ('delta44vh3',ctypes.c_double),
                ('delta44vh6',ctypes.c_double),
                ('delta44vh6S',ctypes.c_double),
                ('delta44v5',ctypes.c_double),
                ('delta44vh9',ctypes.c_double),
                ('rho44v2',ctypes.c_double),
                ('rho44v3',ctypes.c_double),
                ('rho44v3S',ctypes.c_double),
                ('rho44v4',ctypes.c_double),
                ('rho44v4S',ctypes.c_double),
                ('rho44v5',ctypes.c_double),
                ('rho44v5S',ctypes.c_double),
                ('rho44v6',ctypes.c_double),
                ('rho44v6S',ctypes.c_double),
                ('rho44v6l',ctypes.c_double),
                ('rho44v8',ctypes.c_double),
                ('rho44v8l',ctypes.c_double),
                ('rho44v10',ctypes.c_double),
                ('rho44v10l',ctypes.c_double),
                ('delta43vh3',ctypes.c_double),
                ('delta43vh4',ctypes.c_double),
                ('delta43vh4S',ctypes.c_double),
                ('delta43vh6',ctypes.c_double),
                ('rho43v',ctypes.c_double),
                ('rho43v2',ctypes.c_double),
                ('rho43v4',ctypes.c_double),
                ('rho43v4S',ctypes.c_double),
                ('rho43v5',ctypes.c_double),
                ('rho43v5S',ctypes.c_double),
                ('rho43v6',ctypes.c_double),
                ('rho43v6l',ctypes.c_double),
                ('f43v',ctypes.c_double),
                ('f43vS',ctypes.c_double),
                ('delta42vh3',ctypes.c_double),
                ('delta42vh6',ctypes.c_double),
                ('delta42vh6S',ctypes.c_double),
                ('rho42v2',ctypes.c_double),
                ('rho42v3',ctypes.c_double),
                ('rho42v3S',ctypes.c_double),
                ('rho42v4',ctypes.c_double),
                ('rho42v4S',ctypes.c_double),
                ('rho42v5',ctypes.c_double),
                ('rho42v5S',ctypes.c_double),
                ('rho42v6',ctypes.c_double),
                ('rho42v6S',ctypes.c_double),
                ('rho42v6l',ctypes.c_double),
                ('delta41vh3',ctypes.c_double),
                ('delta41vh4',ctypes.c_double),
                ('delta41vh4S',ctypes.c_double),
                ('delta41vh6',ctypes.c_double),
                ('rho41v',ctypes.c_double),
                ('rho41v2',ctypes.c_double),
                ('rho41v4',ctypes.c_double),
                ('rho41v4S',ctypes.c_double),
                ('rho41v5',ctypes.c_double),
                ('rho41v5S',ctypes.c_double),
                ('rho41v6',ctypes.c_double),
                ('rho41v6l',ctypes.c_double),
                ('f41v',ctypes.c_double),
                ('f41vS',ctypes.c_double),
                ('delta55vh3',ctypes.c_double),
                ('delta55vh6',ctypes.c_double),
                ('delta55vh9',ctypes.c_double),
                ('delta55v5',ctypes.c_double),
                ('rho55v2',ctypes.c_double),
                ('rho55v3',ctypes.c_double),
                ('rho55v3S',ctypes.c_double),
                ('rho55v4',ctypes.c_double),
                ('rho55v4S',ctypes.c_double),
                ('rho55v5',ctypes.c_double),
                ('rho55v5S',ctypes.c_double),
                ('rho55v6',ctypes.c_double),
                ('rho55v6l',ctypes.c_double),
                ('rho55v8',ctypes.c_double),
                ('rho55v8l',ctypes.c_double),
                ('rho55v10',ctypes.c_double),
                ('rho55v10l',ctypes.c_double),
                ('f55v3',ctypes.c_double),
                ('f55v4',ctypes.c_double),
                ('f55v5c',ctypes.c_double),
                ('delta54vh3',ctypes.c_double),
                ('delta54vh4',ctypes.c_double),
                ('delta54vh4S',ctypes.c_double),
                ('rho54v2',ctypes.c_double),
                ('rho54v3',ctypes.c_double),
                ('rho54v3S',ctypes.c_double),
                ('rho54v4',ctypes.c_double),
                ('rho54v4S',ctypes.c_double),
                ('delta53vh3',ctypes.c_double),
                ('rho53v2',ctypes.c_double),
                ('rho53v3',ctypes.c_double),
                ('rho53v3S',ctypes.c_double),
                ('rho53v4',ctypes.c_double),
                ('rho53v4S',ctypes.c_double),
                ('rho53v5',ctypes.c_double),
                ('rho53v5S',ctypes.c_double),
                ('delta52vh3',ctypes.c_double),
                ('delta52vh4',ctypes.c_double),
                ('delta52vh4S',ctypes.c_double),
                ('rho52v2',ctypes.c_double),
                ('rho52v3',ctypes.c_double),
                ('rho52v3S',ctypes.c_double),
                ('rho52v4',ctypes.c_double),
                ('rho52v4S',ctypes.c_double),
                ('delta51vh3',ctypes.c_double),
                ('rho51v2',ctypes.c_double),
                ('rho51v3',ctypes.c_double),
                ('rho51v3S',ctypes.c_double),
                ('rho51v4',ctypes.c_double),
                ('rho51v4S',ctypes.c_double),
                ('rho51v5',ctypes.c_double),
                ('rho51v5S',ctypes.c_double),
                ('delta66vh3',ctypes.c_double),
                ('rho66v2',ctypes.c_double),
                ('rho66v3',ctypes.c_double),
                ('rho66v3S',ctypes.c_double),
                ('rho66v4',ctypes.c_double),
                ('rho66v4S',ctypes.c_double),
                ('delta65vh3',ctypes.c_double),
                ('rho65v2',ctypes.c_double),
                ('rho65v3',ctypes.c_double),
                ('rho65v3S',ctypes.c_double),
                ('delta64vh3',ctypes.c_double),
                ('rho64v2',ctypes.c_double),
                ('rho64v3',ctypes.c_double),
                ('rho64v3S',ctypes.c_double),
                ('rho64v4',ctypes.c_double),
                ('rho64v4S',ctypes.c_double),
                ('delta63vh3',ctypes.c_double),
                ('rho63v2',ctypes.c_double),
                ('rho63v3',ctypes.c_double),
                ('rho63v3S',ctypes.c_double),
                ('delta62vh3',ctypes.c_double),
                ('rho62v2',ctypes.c_double),
                ('rho62v3',ctypes.c_double),
                ('rho62v3S',ctypes.c_double),
                ('rho62v4',ctypes.c_double),
                ('rho62v4S',ctypes.c_double),
                ('delta61vh3',ctypes.c_double),
                ('rho61v2',ctypes.c_double),
                ('rho61v3',ctypes.c_double),
                ('rho61v3S',ctypes.c_double),
                ('delta77vh3',ctypes.c_double),
                ('rho77v2',ctypes.c_double),
                ('rho77v3',ctypes.c_double),
                ('rho77v3S',ctypes.c_double),
                ('rho76v2',ctypes.c_double),
                ('delta75vh3',ctypes.c_double),
                ('rho75v2',ctypes.c_double),
                ('rho75v3',ctypes.c_double),
                ('rho75v3S',ctypes.c_double),
                ('rho74v2',ctypes.c_double),
                ('delta73vh3',ctypes.c_double),
                ('rho73v2',ctypes.c_double),
                ('rho73v3',ctypes.c_double),
                ('rho73v3S',ctypes.c_double),
                ('rho72v2',ctypes.c_double),
                ('delta71vh3',ctypes.c_double),
                ('rho71v2',ctypes.c_double),
                ('rho71v3',ctypes.c_double),
                ('rho71v3S',ctypes.c_double),
                ('rho88v2',ctypes.c_double),
                ('rho87v2',ctypes.c_double),
                ('rho86v2',ctypes.c_double),
                ('rho85v2',ctypes.c_double),
                ('rho84v2',ctypes.c_double),
                ('rho83v2',ctypes.c_double),
                ('rho82v2',ctypes.c_double),
                ('rho81v2',ctypes.c_double),
                ('h22T0ff00',ctypes.c_double),
                ('h22T0ff02',ctypes.c_double),
                ('h22T0ff20',ctypes.c_double),
                ('h22T0ff11',ctypes.c_double),
                ('h22T2ff00',c_complex),
                ('h22T2ff02',ctypes.c_double),
                ('h22T2ff20',ctypes.c_double),
                ('h22T2ff11',ctypes.c_double),
                ('h22T2ff40',ctypes.c_double),
                ('h22T2ff31',ctypes.c_double),
                ('h22T2ff22',ctypes.c_double),
                ('h22T2ff13',ctypes.c_double),
                ('h22T2ff04',ctypes.c_double),
                ('h22T3ff10',ctypes.c_double),
                ('h22T3ff01',ctypes.c_double),
                ('h22T3ff30',ctypes.c_double),
                ('h22T3ff21',ctypes.c_double),
                ('h22T3ff12',ctypes.c_double),
                ('h22T3ff03',ctypes.c_double),
                ('h22T4ff00',c_complex),
                ('h22T4ff20',c_complex),
                ('h22T4ff11',c_complex),
                ('h22T4ff02',c_complex),
                ('h22T4ff40',ctypes.c_double),
                ('h22T4ff31',ctypes.c_double),
                ('h22T4ff22',ctypes.c_double),
                ('h22T4ff13',ctypes.c_double),
                ('h22T4ff04',ctypes.c_double),
                ('h22T4ff60',ctypes.c_double),
                ('h22T4ff51',ctypes.c_double),
                ('h22T4ff42',ctypes.c_double),
                ('h22T4ff33',ctypes.c_double),
                ('h22T4ff24',ctypes.c_double),
                ('h22T4ff15',ctypes.c_double),
                ('h22T4ff06',ctypes.c_double),
                ('h21T0ff01',ctypes.c_double),
                ('h21T1ff00',ctypes.c_double),
                ('h21T2ff21',ctypes.c_double),
                ('h21T2ff12',ctypes.c_double),
                ('h21T2ff10',ctypes.c_double),
                ('h21T2ff03',ctypes.c_double),
                ('h21T2ff01',c_complex),
                ('h21T3ff20',ctypes.c_double),
                ('h21T3ff11',ctypes.c_double),
                ('h21T3ff02',ctypes.c_double),
                ('h21T3ff00',c_complex),
                ('h33T0ff30',ctypes.c_double),
                ('h33T0ff21',ctypes.c_double),
                ('h33T0ff12',ctypes.c_double),
                ('h33T0ff10',ctypes.c_double),
                ('h33T0ff03',ctypes.c_double),
                ('h33T0ff01',ctypes.c_double),
                ('h33T2ff50',ctypes.c_double),
                ('h33T2ff41',ctypes.c_double),
                ('h33T2ff32',ctypes.c_double),
                ('h33T2ff30',ctypes.c_double),
                ('h33T2ff23',ctypes.c_double),
                ('h33T2ff21',ctypes.c_double),
                ('h33T2ff14',ctypes.c_double),
                ('h33T2ff12',ctypes.c_double),
                ('h33T2ff10',c_complex),
                ('h33T2ff05',ctypes.c_double),
                ('h33T2ff03',ctypes.c_double),
                ('h33T2ff01',c_complex),
                ('h33T3ff20',ctypes.c_double),
                ('h33T3ff11',ctypes.c_double),
                ('h33T3ff02',ctypes.c_double),
                ('h33T3ff00',ctypes.c_double),
                ('h33T3ff40',ctypes.c_double),
                ('h33T3ff31',ctypes.c_double),
                ('h33T3ff22',ctypes.c_double),
                ('h33T3ff13',ctypes.c_double),
                ('h32T0ff11',ctypes.c_double),
                ('h32T0ff02',ctypes.c_double),
                ('h32T1ff10',ctypes.c_double),
                ('h32T1ff01',ctypes.c_double),
                ('h32T2ff31',ctypes.c_double),
                ('h32T2ff22',ctypes.c_double),
                ('h32T2ff13',ctypes.c_double),
                ('h32T2ff11',ctypes.c_double),
                ('h32T2ff04',ctypes.c_double),
                ('h32T2ff02',ctypes.c_double),
                ('h31T0ff30',ctypes.c_double),
                ('h31T0ff21',ctypes.c_double),
                ('h31T0ff12',ctypes.c_double),
                ('h31T0ff10',ctypes.c_double),
                ('h31T0ff03',ctypes.c_double),
                ('h31T0ff01',ctypes.c_double),
                ('h31T2ff50',ctypes.c_double),
                ('h31T2ff41',ctypes.c_double),
                ('h31T2ff32',ctypes.c_double),
                ('h31T2ff30',ctypes.c_double),
                ('h31T2ff23',ctypes.c_double),
                ('h31T2ff21',ctypes.c_double),
                ('h31T2ff14',ctypes.c_double),
                ('h31T2ff12',ctypes.c_double),
                ('h31T2ff10',ctypes.c_double),
                ('h31T2ff05',ctypes.c_double),
                ('h31T2ff03',ctypes.c_double),
                ('h31T2ff01',ctypes.c_double),
                ('h31T3ff20',ctypes.c_double),
                ('h31T3ff11',ctypes.c_double),
                ('h31T3ff02',ctypes.c_double),
                ('h31T3ff00',ctypes.c_double),
                ('h44T0ff40',ctypes.c_double),
                ('h44T0ff31',ctypes.c_double),
                ('h44T0ff22',ctypes.c_double),
                ('h44T0ff20',ctypes.c_double),
                ('h44T0ff13',ctypes.c_double),
                ('h44T0ff11',ctypes.c_double),
                ('h44T0ff04',ctypes.c_double),
                ('h44T0ff02',ctypes.c_double),
                ('h44T0ff00',ctypes.c_double),
                ('h44T2ff60',ctypes.c_double),
                ('h44T2ff51',ctypes.c_double),
                ('h44T2ff42',ctypes.c_double),
                ('h44T2ff40',ctypes.c_double),
                ('h44T2ff31',ctypes.c_double),
                ('h44T2ff24',ctypes.c_double),
                ('h44T2ff22',ctypes.c_double),
                ('h44T2ff20',c_complex),
                ('h44T2ff15',ctypes.c_double),
                ('h44T2ff13',ctypes.c_double),
                ('h44T2ff11',c_complex),
                ('h44T2ff06',ctypes.c_double),
                ('h44T2ff04',ctypes.c_double),
                ('h44T2ff02',c_complex),
                ('h44T2ff00',c_complex),
                ('h43T0ff21',ctypes.c_double),
                ('h43T0ff12',ctypes.c_double),
                ('h43T0ff03',ctypes.c_double),
                ('h43T0ff01',ctypes.c_double),
                ('h43T1ff20',ctypes.c_double),
                ('h43T1ff11',ctypes.c_double),
                ('h43T1ff02',ctypes.c_double),
                ('h43T1ff00',ctypes.c_double),
                ('h42T0ff40',ctypes.c_double),
                ('h42T0ff31',ctypes.c_double),
                ('h42T0ff20',ctypes.c_double),
                ('h42T0ff13',ctypes.c_double),
                ('h42T0ff11',ctypes.c_double),
                ('h42T0ff04',ctypes.c_double),
                ('h42T0ff02',ctypes.c_double),
                ('h42T0ff00',ctypes.c_double),
                ('h42T2ff60',ctypes.c_double),
                ('h42T2ff51',ctypes.c_double),
                ('h42T2ff42',ctypes.c_double),
                ('h42T2ff40',ctypes.c_double),
                ('h42T2ff33',ctypes.c_double),
                ('h42T2ff31',ctypes.c_double),
                ('h42T2ff24',ctypes.c_double),
                ('h42T2ff22',ctypes.c_double),
                ('h42T2ff20',ctypes.c_double),
                ('h42T2ff15',ctypes.c_double),
                ('h42T2ff13',ctypes.c_double),
                ('h42T2ff11',ctypes.c_double),
                ('h42T2ff06',ctypes.c_double),
                ('h42T2ff04',ctypes.c_double),
                ('h42T2ff02',ctypes.c_double),
                ('h42T2ff00',ctypes.c_double),
                ('h41T0ff21',ctypes.c_double),
                ('h41T0ff12',ctypes.c_double),
                ('h41T0ff03',ctypes.c_double),
                ('h41T0ff01',ctypes.c_double),
                ('h41T1ff20',ctypes.c_double),
                ('h41T1ff11',ctypes.c_double),
                ('h41T1ff02',ctypes.c_double),
                ('h41T1ff02',ctypes.c_double))

class pyEOBNonQCCoeffs(ctypes.Structure):
    _fields_ = (('a1', ctypes.c_double),
                ('a2', ctypes.c_double),
                ('a3', ctypes.c_double),
                ('a3S', ctypes.c_double),
                ('a4', ctypes.c_double),
                ('a5', ctypes.c_double),
                ('b1', ctypes.c_double),
                ('b2', ctypes.c_double),
                ('b3', ctypes.c_double),
                ('b4', ctypes.c_double))

class pySpinEOBHCoeffs(ctypes.Structure):
    _fields_ = (('KK', ctypes.c_double),
                ('k0', ctypes.c_double),
                ('k1', ctypes.c_double),
                ('k2', ctypes.c_double),
                ('k3', ctypes.c_double),
                ('k4', ctypes.c_double),
                ('k5', ctypes.c_double),
                ('k5l', ctypes.c_double),
                ('b3', ctypes.c_double),
                ('bb3', ctypes.c_double),
                ('d1', ctypes.c_double),
                ('d1v2', ctypes.c_double),
                ('dheffSS', ctypes.c_double),
                ('dheffSSv2', ctypes.c_double),
                ('updateHCoeffs', ctypes.c_double))

class pySpinEOBHSACoeffs(ctypes.Structure):
    _fields_ = (('eta',ctypes.c_double),
            ('a',ctypes.c_double),
            ('a2',ctypes.c_double),
            ('chi',ctypes.c_double),
            ('sigmaStar',ctypes.c_double),
            ('sigmaKerr',ctypes.c_double),
            ('invm1PlusEtaKK',ctypes.c_double),
            ('k0',ctypes.c_double),
            ('k1',ctypes.c_double),
            ('k2',ctypes.c_double),
            ('k3',ctypes.c_double),
            ('k4',ctypes.c_double),
            ('k5',ctypes.c_double),
            ('k5l',ctypes.c_double),
            ('D2',ctypes.c_double),
            ('D3',ctypes.c_double),
            ('b3',ctypes.c_double),
            ('bb3',ctypes.c_double),
            ('PQ4',ctypes.c_double),
            ('Pds0u',ctypes.c_double),
            ('Pds0p2',ctypes.c_double),
            ('Pds0pn2',ctypes.c_double),
            ('PdsSu2',ctypes.c_double),
            ('PdsSup2',ctypes.c_double),
            ('PdsSpn4',ctypes.c_double),
            ('PdsSp4',ctypes.c_double),
            ('PdsSupn2',ctypes.c_double),
            ('PdsSp2pn2',ctypes.c_double),
            ('PdsKu2',ctypes.c_double),
            ('PdsKup2',ctypes.c_double),
            ('PdsKpn4',ctypes.c_double),
            ('PdsKp4',ctypes.c_double),
            ('PdsKupn2',ctypes.c_double),
            ('PdsKp2pn2',ctypes.c_double),
            ('PdsKu3',ctypes.c_double),
            ('PdsKu3',ctypes.c_double))

class pySEOBHCoeffConstants(ctypes.Structure):
    _fields_ = (('a0k2',ctypes.c_double),
                ('a1k2',ctypes.c_double),
                ('a0k3',ctypes.c_double),
                ('a1k3',ctypes.c_double),
                ('a0k4',ctypes.c_double),
                ('a1k4',ctypes.c_double),
                ('a2k4',ctypes.c_double),
                ('a0k5',ctypes.c_double),
                ('a1k5',ctypes.c_double),
                ('a1k5',ctypes.c_double))

class pyNewtonMultipolePrefixes(ctypes.Structure):
    _fields_ = [('values',(c_complex*9)*9)]

class pyEccCorrectionCoeffs(ctypes.Structure):
    _fields_ = (('FrPN1_f21',ctypes.c_double),
                ('FrPN1_f20',ctypes.c_double),
                ('FrPN1_f12',ctypes.c_double),
                ('FrPN1_f11',ctypes.c_double),
                ('FrPN1_f10',ctypes.c_double),
                ('FrPN1_f03',ctypes.c_double),
                ('FrPN1_f02',ctypes.c_double),
                ('FrPN1_f01',ctypes.c_double),
                ('FfPN1_f21',ctypes.c_double),
                ('FfPN1_f20',ctypes.c_double),
                ('FfPN1_f12',ctypes.c_double),
                ('FfPN1_f11',ctypes.c_double),
                ('FfPN1_f10',ctypes.c_double),
                ('FfPN1_f03',ctypes.c_double),
                ('FfPN1_f02',ctypes.c_double),
                ('FfPN1_f01',ctypes.c_double),
                ('FrPN32_f21',ctypes.c_double),
                ('FrPN32_f20',ctypes.c_double),
                ('FrPN32_f11',ctypes.c_double),
                ('FrPN32_f10',ctypes.c_double),
                ('FrPN32_f02',ctypes.c_double),
                ('FrPN32_f01',ctypes.c_double),
                ('FfPN32_f30',ctypes.c_double),
                ('FfPN32_f20',ctypes.c_double),
                ('FfPN32_f11',ctypes.c_double),
                ('FfPN32_f10',ctypes.c_double),
                ('FfPN32_f02',ctypes.c_double),
                ('FfPN32_f01',ctypes.c_double),
                ('FrPN2Topfm2_f20',ctypes.c_double),
                ('FrPN2Topfm2_f10',ctypes.c_double),
                ('FrPN2Topfm2_f00',ctypes.c_double),
                ('FrPN2Topfm1_f20',ctypes.c_double),
                ('FrPN2Topfm1_f10',ctypes.c_double),
                ('FrPN2Topfm1_f00',ctypes.c_double),
                ('FrPN2Topf0_f30',ctypes.c_double),
                ('FrPN2Topf0_f21',ctypes.c_double),
                ('FrPN2Topf0_f20',ctypes.c_double),
                ('FrPN2Topf0_f12',ctypes.c_double),
                ('FrPN2Topf0_f11',ctypes.c_double),
                ('FrPN2Topf0_f10',ctypes.c_double),
                ('FrPN2Topf0_f03',ctypes.c_double),
                ('FrPN2Topf0_f02',ctypes.c_double),
                ('FrPN2Topf0_f01',ctypes.c_double),
                ('FrPN2Topf0_f00',ctypes.c_double),
                ('FfPN2Topfm2_f23',ctypes.c_double),
                ('FfPN2Topfm2_f14',ctypes.c_double),
                ('FfPN2Topfm2_f05',ctypes.c_double),
                ('FfPN2Topfm1_f22',ctypes.c_double),
                ('FfPN2Topfm1_f13',ctypes.c_double),
                ('FfPN2Topfm1_f04',ctypes.c_double),
                ('FfPN2Topf0_f30',ctypes.c_double),
                ('FfPN2Topf0_f21',ctypes.c_double),
                ('FfPN2Topf0_f20',ctypes.c_double),
                ('FfPN2Topf0_f12',ctypes.c_double),
                ('FfPN2Topf0_f11',ctypes.c_double),
                ('FfPN2Topf0_f10',ctypes.c_double),
                ('FfPN2Topf0_f03',ctypes.c_double),
                ('FfPN2Topf0_f02',ctypes.c_double),
                ('FfPN2Topf0_f02',ctypes.c_double))

# Core: Spin EOB Parameters
class pySpinEOBParams(ctypes.Structure):
    _fields_ = (('eta', ctypes.c_double),
                ('m1', ctypes.c_double),
                ('m2', ctypes.c_double),
                ('a', ctypes.c_double),
                ('chi1', ctypes.c_double),
                ('chi2', ctypes.c_double),
                ('p0', ctypes.c_double),
                ('e0', ctypes.c_double),
                ('x0', ctypes.c_double),
                ('omega', ctypes.c_double),
                ('omegaPeaked', ctypes.c_uint),
                ('termination_reason', ctypes.c_int),
                ('prev_dr', ctypes.c_double),
                ('spin1z_omegaPeak', ctypes.c_double),
                ('spin2z_omegaPeak', ctypes.c_double),
                ('tPeakOmega', ctypes.c_double),
                ('s1Vec', ctypes.POINTER(pyREAL8Vector)),
                ('s2Vec', ctypes.POINTER(pyREAL8Vector)),
                ('sigmaStar', ctypes.POINTER(pyREAL8Vector)),
                ('sigmaKerr', ctypes.POINTER(pyREAL8Vector)),
                ('J0Vec', ctypes.POINTER(pyREAL8Vector)),
                ('J0Vec', ctypes.POINTER(pyREAL8Vector)),
                ('seobCoeffs', ctypes.POINTER(pySpinEOBHCoeffs)),
                ('saCoeffs', ctypes.POINTER(pySpinEOBHSACoeffs)),
                ('seobCoeffConsts', ctypes.POINTER(pySEOBHCoeffConstants)),
                ('hParams', ctypes.POINTER(pyHyperParams)),
                ('prefixes', ctypes.POINTER(pyNewtonMultipolePrefixes)),
                ('hCoeffs', ctypes.POINTER(pyFacWaveformCoeffs)),
                ('eccCoeffs', ctypes.POINTER(pyEccCorrectionCoeffs)),
                ('nqcCoeffs', ctypes.POINTER(pyEOBNonQCCoeffs)),
                ('cal21',c_complex),
                ('cal21E',ctypes.c_double),
                ('cal21E1',ctypes.c_double),
                ('cal21E2',ctypes.c_double),
                ('cal21E3',ctypes.c_double),
                ('cal21E4',ctypes.c_double),
                ('cal21E4',ctypes.c_double),
                ('tWind',ctypes.c_double),
                ('tWind',ctypes.c_double),
                ('tortoise',ctypes.c_int),
                ('alignedSpins',ctypes.c_int),
                ('ignoreflux',ctypes.c_int),
                ('use_hm',ctypes.c_int),
                ('cache',ctypes.c_double*3)
                )





class pyInputParams(ctypes.Structure):
    _fields_ = (('use_geom', ctypes.c_int), 
                ('m1', ctypes.c_double),
                ('m2', ctypes.c_double),
                ('s1x', ctypes.c_double),
                ('s1y', ctypes.c_double),
                ('s1z', ctypes.c_double),
                ('s2x', ctypes.c_double),
                ('s2y', ctypes.c_double),
                ('s2z', ctypes.c_double),
                ('ecc', ctypes.c_double),
                ('inc', ctypes.c_double),
                ('phiRef', ctypes.c_double),
                ('beta', ctypes.c_double),
                ('f_min', ctypes.c_double),
                ('distance', ctypes.c_double),
                ('srate', ctypes.c_double),
                ('deltaT', ctypes.c_double),
                ('is_only22', ctypes.c_int),
                ('is_constp', ctypes.c_int),
                ('conserve_flag', ctypes.c_int),
                ('conserve_time', ctypes.c_double),
                ('is_noringdown', ctypes.c_int),
                ('prec_flag', ctypes.c_int),
                ('debug_id', ctypes.c_int),
                ('d_ini', ctypes.c_double),
                ('pr_ini', ctypes.c_double),
                ('pphi_ini', ctypes.c_double),
                ('ptheta_ini', ctypes.c_double),
                ('flagTuning', ctypes.c_int),
                ('tStepBack', ctypes.c_double),
                ('sl_p', ctypes.c_double),
                ('x0', ctypes.c_double),
                ('code_version', ctypes.c_int),
                ('log_level', ctypes.c_int),
                ('risco', ctypes.c_double),
                ('KK', ctypes.c_double),
                ('dSS', ctypes.c_double),
                ('dSO', ctypes.c_double),
                ('dtPeak', ctypes.c_double),
                ('egw_flag', ctypes.c_int),
                ('ret_dyn', ctypes.c_int),
                ('inEPS_REL', ctypes.c_double),
                ('inEPS_ABS', ctypes.c_double),
                ('is_coframe', ctypes.c_int),
                ('use_coaphase', ctypes.c_int),
                ('zeta', ctypes.c_double))


class pyOutputStruct(ctypes.Structure):
    _fields_ = (('length', ctypes.c_int),
                ('time', ctypes.POINTER(pyREAL8Vector)),
                ('timeM', ctypes.POINTER(pyREAL8Vector)),
                ('hplus', ctypes.POINTER(pyREAL8Vector)),
                ('hcross', ctypes.POINTER(pyREAL8Vector)),
                ('h22_real', ctypes.POINTER(pyREAL8Vector)),
                ('h22_imag', ctypes.POINTER(pyREAL8Vector)),
                ('h21_real', ctypes.POINTER(pyREAL8Vector)),
                ('h21_imag', ctypes.POINTER(pyREAL8Vector)),
                ('h33_real', ctypes.POINTER(pyREAL8Vector)),
                ('h33_imag', ctypes.POINTER(pyREAL8Vector)),
                ('h44_real', ctypes.POINTER(pyREAL8Vector)),
                ('h44_imag', ctypes.POINTER(pyREAL8Vector)),
                ('h55_real', ctypes.POINTER(pyREAL8Vector)),
                ('h55_imag', ctypes.POINTER(pyREAL8Vector)))

class pyDynOutputStruct(ctypes.Structure):
    _fields_ = (('length', ctypes.c_int),
                ('timeM', ctypes.POINTER(pyREAL8Vector)),
                ('xVec', ctypes.POINTER(pyREAL8Vector)),
                ('yVec', ctypes.POINTER(pyREAL8Vector)),
                ('zVec', ctypes.POINTER(pyREAL8Vector)),
                ('pTxVec', ctypes.POINTER(pyREAL8Vector)),
                ('pTyVec', ctypes.POINTER(pyREAL8Vector)),
                ('pTzVec', ctypes.POINTER(pyREAL8Vector)),
                ('vxVec', ctypes.POINTER(pyREAL8Vector)),
                ('vyVec', ctypes.POINTER(pyREAL8Vector)),
                ('vzVec', ctypes.POINTER(pyREAL8Vector)),
                ('s1xVec', ctypes.POINTER(pyREAL8Vector)),
                ('s1yVec', ctypes.POINTER(pyREAL8Vector)),
                ('s1zVec', ctypes.POINTER(pyREAL8Vector)),
                ('s2xVec', ctypes.POINTER(pyREAL8Vector)),
                ('s2yVec', ctypes.POINTER(pyREAL8Vector)),
                ('s2zVec', ctypes.POINTER(pyREAL8Vector)),
                ('prTDotVec', ctypes.POINTER(pyREAL8Vector)),
                ('hamVec', ctypes.POINTER(pyREAL8Vector))
                )
